# cluster size
numberofnodes: 1
#nodes_to_exclude: 1,2,3,4,5,6,7,8,9
#cluster name, bid's and tasks will use it
tag: "TEST"

# final price = predicted price * (1 + price_coefficient/100)
price_coefficient: 10

# $ per hour
max_price: "0.02"

# Estimated time of successful start of task (blacklist worker if task failed before ets)
ets: 180

task_start_timeout: 600

# Template for task yaml
template_file: "claymore_task.yaml"

# duration ("0h" for spot deals; "4h" (for example) for forward deals)
duration: 0h

# optional, sets counterparty for orders to take, must be HEX(40) string. Will be removed automatically in case of error/not set
counterparty: ""
# Identity level of the counterparty. Can be "anonymous", "registered", "identified" and "professional".
identity: "anonymous"

resources:
  # Network settings
  network:
    # Indicates whether overlay networking is required, boolean only
    overlay: false
    outbound: true
    # Indicates whether inbound connections are required and public IP should be present on worker, boolean only
    incoming: false
  # Other benchmarks
  benchmarks:
    # MB, integers only
    ram-size: 2000
    # GB, integers only
    storage-size: 1
    #number of cores, integers only
    cpu-cores: 1
    cpu-sysbench-single: 500
    cpu-sysbench-multi: 1000
    # Mbits, integers only
    net-download: 10
    # Mbits, integers only
    net-upload: 10
    # GPU unit RAM,MB, integers only
    gpu-count: 1
    # GPU unit RAM,MB, integers only
    gpu-mem: 2900
    # MH/s, integers only
    gpu-eth-hashrate: 0
